// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type BirthdayNotification struct {
	ID          int32
	PersonID    string
	ScheduledAt string
	State       string
}

type Person struct {
	ID        string
	Name      string
	BirthDate string
}
