services:
  db:
    env_file: ".env.prod"
    image: postgres:16.3
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    env_file: ".env.prod"
    # build: ghcr.io/marnickvda/birthday-tracker:0.1.0
    build:
      dockerfile: Dockerfile
    container_name: birthday-tracker
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge